# Generated by Django 5.1.5 on 2025-02-28 04:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('photo', models.ImageField(upload_to='pets_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91XXXXXXXXXX'. Up to 10 digits allowed after '+91'.", regex='^\\+91\\d{10}$')])),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('guest', 'Guest'), ('admin', 'Admin')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='pet_photos/')),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('fish', 'fish'), ('other', 'Other')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('cost', models.IntegerField()),
                ('health_status', models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('vaccinated', 'Vaccinated'), ('neutered', 'Neutered'), ('special_needs', 'Special Needs'), ('other', 'Other')], max_length=20)),
                ('personality_traits', models.TextField(help_text='Describe the pet’s personality')),
                ('adoption_status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted')], default='available', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(default='Not specified', help_text='enter city or address', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='petzeno.user')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petzeno.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petzeno.user')),
            ],
        ),
    ]
