# Generated by Django 5.1.5 on 2025-02-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petzeno', '0001_initial'),
    ]

    operations = [
    ]
