# Generated by Django 5.1.5 on 2025-03-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzeno', '0004_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
