# Generated by Django 5.1.5 on 2025-03-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzeno', '0006_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='petzeno.order', unique=True),
        ),
    ]
