# Generated by Django 5.1.5 on 2025-03-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petzeno', '0007_alter_form_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
