# Generated by Django 5.1.5 on 2025-03-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petzeno', '0009_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='notes',
        ),
    ]
