# Generated by Django 5.1.5 on 2025-03-02 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzeno', '0010_remove_form_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91XXXXXXXXXX'. Up to 10 digits allowed after '+91'.", regex='^\\+91\\d{10}$')]),
        ),
    ]
