# Generated by Django 5.1.5 on 2025-05-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petzeno', '0011_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('fish', 'fish'), ('other', 'Other')], max_length=100),
        ),
    ]
